    alter table if exists credit_product_additive
        alter column interest_rate type numeric;
    
    create table aud_payment_transaction (
        id bigint not null,
        rev integer not null,
        participant varchar(31) not null,
        revtype smallint,
        amount_currency varchar(3),
        amount_number numeric(19,2),
        completed_at timestamp(6) with time zone,
        description varchar(32600),
        exported_at timestamp(6) with time zone,
        external_id varchar(255),
        service varchar(255),
        status integer,
        trace varchar(32600),
        type integer,
        payment_method_id bigint,
        refund_target bigint,
        credit_id uuid,
        primary key (rev, id)
    );

    create table payment_method (
        d_type varchar(31) not null,
        id bigint generated by default as identity,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        active boolean not null,
        exported_id varchar(255),
        token varchar(255),
        amount_currency varchar(3),
        amount_number numeric(19,2),
        name varchar(255),
        processed_date date,
        transaction_type integer,
        created_by uuid,
        updated_by uuid,
        primary key (id)
    );

    create table payment_transaction (
        participant varchar(31) not null,
        id bigint generated by default as identity,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        amount_currency varchar(3),
        amount_number numeric(19,2),
        completed_at timestamp(6) with time zone,
        description varchar(32600),
        exported_at timestamp(6) with time zone,
        external_id varchar(255),
        service varchar(255),
        status integer not null,
        trace varchar(32600),
        type integer not null,
        created_by uuid,
        updated_by uuid,
        payment_method_id bigint,
        refund_target bigint,
        credit_id uuid,
        operation_id uuid,
        primary key (id)
    );

    alter table if exists payment_transaction 
       drop constraint if exists UK4ouv9847hue00f2laj6bxmaia;

    alter table if exists payment_transaction 
       add constraint UK4ouv9847hue00f2laj6bxmaia unique (type, service, external_id);

    alter table if exists payment_transaction 
       drop constraint if exists UK787hqcqcnh2is7miacnlm1ct5;

    alter table if exists payment_transaction 
       add constraint UK787hqcqcnh2is7miacnlm1ct5 unique (refund_target);

    alter table if exists aud_payment_transaction 
       add constraint FK6fsw1minlfogcxhutia5w7nn0 
       foreign key (rev) 
       references aud;

    alter table if exists payment_method 
       add constraint FKjg5dabiscd9aj8bni307edhr9 
       foreign key (created_by) 
       references auditor;

    alter table if exists payment_method 
       add constraint FKm5mqy5l1as8pa2ijywk6re4xg 
       foreign key (updated_by) 
       references auditor;

    alter table if exists payment_transaction 
       add constraint FKroxkwyi3w698t2iyoriivtjvu 
       foreign key (created_by) 
       references auditor;

    alter table if exists payment_transaction 
       add constraint FKeb86kusjxu7vuv2enrju9qsi 
       foreign key (updated_by) 
       references auditor;

    alter table if exists payment_transaction 
       add constraint FK6cusxtyx23t11e5jmdeq1anb3 
       foreign key (payment_method_id) 
       references payment_method;

    alter table if exists payment_transaction 
       add constraint FKolg6u0dks1f0nclr90br68afd 
       foreign key (refund_target) 
       references payment_transaction;

    alter table if exists payment_transaction 
       add constraint FKr6frnl9qayufwi5c48x987obw 
       foreign key (credit_id) 
       references credit;

    alter table if exists payment_transaction 
       add constraint FKsjri37072u8qixt9ikirh35n5 
       foreign key (operation_id) 
       references credit_operation;
