
    alter table if exists credit_product 
       add column dtype varchar(31) not null;

    alter table if exists credit_product 
       add column currency varchar(255);

    alter table if exists credit_product 
       add column max_amount numeric(19,2) not null;

    alter table if exists credit_product 
       add column max_term integer not null;

    alter table if exists credit_product 
       add column min_amount numeric(19,2) not null;

    alter table if exists credit_product 
       add column min_term integer not null;


    create table aud_product_offer (
                                       id bigint not null,
                                       rev integer not null,
                                       revtype smallint,
                                       max_amount numeric(19,2),
                                       max_term integer,
                                       min_amount numeric(19,2),
                                       min_term integer,
                                       product_additive bigint,
                                       participant_id uuid,
                                       primary key (rev, id)
    );

    alter table if exists credit_product_additive
        add column dtype varchar(31) not null;

    alter table if exists credit_product_additive
        add column max_amount numeric(19,2) not null;

    alter table if exists credit_product_additive
        add column max_term integer not null;

    alter table if exists credit_product_additive
        add column min_amount numeric(19,2) not null;

    alter table if exists credit_product_additive
        add column min_term integer not null;

    alter table if exists credit_product_additive
        add column name varchar(255) not null;

    create table product_offer (
                                   id bigint generated by default as identity,
                                   created_at timestamp(6) with time zone not null,
                                   updated_at timestamp(6) with time zone not null,
                                   max_amount numeric(19,2) not null,
                                   max_term integer not null,
                                   min_amount numeric(19,2) not null,
                                   min_term integer not null,
                                   uuid uuid default gen_random_uuid() not null,
                                   created_by uuid,
                                   updated_by uuid,
                                   product_additive bigint not null,
                                   participant_id uuid not null,
                                   primary key (id)
    );

    alter table if exists aud_product_offer
        add constraint FKaa53wrei5ea0afxpblhc3vb43
            foreign key (rev)
                references aud;

    alter table if exists product_offer
        add constraint FKk4d6of4y0dtxlmbou2o958bg4
            foreign key (created_by)
                references auditor;

    alter table if exists product_offer
        add constraint FK7ebreerjthwk49fim7j3a6jul
            foreign key (updated_by)
                references auditor;

    alter table if exists product_offer
        add constraint FK9iumthhspmdn2csnromqbaq6b
            foreign key (product_additive)
                references credit_product_additive;

    alter table if exists product_offer
        add constraint FKtj5qkemp3nrat1bu4p8g2f0yg
            foreign key (participant_id)
                references participant;


    create table aud_credit_operation (
                                          id uuid not null,
                                          rev integer not null,
                                          operation_type integer not null,
                                          revtype smallint,
                                          date date,
                                          status integer,
                                          amount_currency varchar(3),
                                          amount_number numeric(19,2),
                                          ledger varchar(255),
                                          initial_amount numeric(19,2),
                                          primary key (rev, id)
    );

    create table credit (
                            credit_type integer not null,
                            id uuid not null,
                            calculation_date date,
                            created_at timestamp(6) with time zone not null,
                            start_date date not null,
                            updated_at timestamp(6) with time zone not null,
                            actual_snapshot bigint,
                            created_by uuid,
                            updated_by uuid,
                            primary key (id)
    );

    create table credit_condition (
                                      id uuid not null,
                                      annual_interest numeric not null,
                                      engine_name varchar(255) not null,
                                      period varchar(255) not null,
                                      principal_currency varchar(3),
                                      principal_number numeric(19,2),
                                      term integer not null,
                                      primary key (id)
    );

    create table credit_operation (
                                      operation_type integer not null,
                                      id uuid not null,
                                      created_at timestamp(6) with time zone not null,
                                      updated_at timestamp(6) with time zone not null,
                                      date date not null,
                                      status integer not null,
                                      amount_currency varchar(3),
                                      amount_number numeric(19,2),
                                      ledger varchar(255),
                                      initial_amount numeric(19,2),
                                      created_by uuid,
                                      updated_by uuid,
                                      credit_id uuid,
                                      primary key (id)
    );

    create table credit_operation_distribution (
                                                   id bigint generated by default as identity,
                                                   debt jsonb not null,
                                                   ditributed_at timestamp(6) with time zone,
                                                   type smallint,
                                                   operation_id uuid not null,
                                                   primary key (id)
    );

    create table credit_snapshot (
                                     id bigint generated by default as identity,
                                     date date not null,
                                     debt jsonb not null,
                                     credit_status integer not null,
                                     credit_id uuid not null,
                                     primary key (id)
    );

    alter table if exists credit
        drop constraint if exists UKn0wtng3fvy7frs1irrnu2tow6;

    alter table if exists credit
        add constraint UKn0wtng3fvy7frs1irrnu2tow6 unique (actual_snapshot);

    alter table if exists process_definition
        drop constraint if exists UKihhwmk9753d3b05d7tku8j0mq;

    alter table if exists process_definition
        add constraint UKihhwmk9753d3b05d7tku8j0mq unique (process_definition_id);

    alter table if exists aud_credit_operation
        add constraint FK2vjb1c90manl62jxo5x9k4loc
            foreign key (rev)
                references aud;

    alter table if exists credit
        add constraint FKmo9ac6g08swvec7lrvbpct6pc
            foreign key (actual_snapshot)
                references credit_snapshot;

    alter table if exists credit
        add constraint FKdto109tev7jqi5gns1de87hin
            foreign key (created_by)
                references auditor;

    alter table if exists credit
        add constraint FK6vo1m5s39ua1culej0va7ijis
            foreign key (updated_by)
                references auditor;

    alter table if exists credit_operation
        add constraint FKi3btul7dm55sgycsuirscu6x2
            foreign key (created_by)
                references auditor;

    alter table if exists credit_operation
        add constraint FK8n5refr006a1p9u92vtuong94
            foreign key (updated_by)
                references auditor;

    alter table if exists credit_operation
        add constraint FK3xg1a6v1wj9og7t4fb7whglgf
            foreign key (credit_id)
                references credit;

    alter table if exists credit_operation_distribution
        add constraint FK8q65s5bgn7yddkg32x5albdpt
            foreign key (operation_id)
                references credit_operation;

    alter table if exists credit_snapshot
        add constraint FKt4xamyx3sd7rcu44fmrdyhhby
            foreign key (credit_id)
                references credit;