
create table aud_secured_offer (
                                   id bigint not null,
                                   rev integer not null,
                                   procuring_type varchar(31) not null,
                                   revtype smallint,
                                   max_amount numeric(19,2),
                                   max_term integer,
                                   min_amount numeric(19,2),
                                   min_term integer,
                                   application_id uuid,
                                   original_offer_id bigint,
                                   primary key (rev, id)
);

create table secured_offer (
                               procuring_type varchar(31) not null,
                               id bigint generated by default as identity,
                               created_at timestamp(6) with time zone not null,
                               updated_at timestamp(6) with time zone not null,
                               max_amount numeric(19,2) not null,
                               max_term integer not null,
                               min_amount numeric(19,2) not null,
                               min_term integer not null,
                               created_by uuid,
                               updated_by uuid,
                               application_id uuid not null,
                               original_offer_id bigint not null,
                               primary key (id)
);

alter table if exists aud_secured_offer
    add constraint FK6dockequ98wh14a834mstygdq
        foreign key (rev)
            references aud;

alter table if exists secured_offer
    add constraint FK1l8hfvd48e2we1hemlgfta5w8
        foreign key (created_by)
            references auditor;

alter table if exists secured_offer
    add constraint FKj4pdau2wg023puwvo6t4so4fo
        foreign key (updated_by)
            references auditor;

alter table if exists secured_offer
    add constraint FKm451v8sdkksh3ck21sc4urdch
        foreign key (application_id)
            references application;

alter table if exists secured_offer
    add constraint FKs3x2mylbn8qhapxtuuby06ey2
        foreign key (original_offer_id)
            references product_offer;
