
    create table aud_decision_fact_details (
        code varchar(255) not null,
        rev integer not null,
        revtype smallint,
        description varchar(255),
        primary key (rev, code)
    );

    create table aud_decision_maker_type (
        rev integer not null,
        decision_fact_details_code varchar(255) not null,
        type varchar(255) not null,
        revtype smallint,
        primary key (decision_fact_details_code, rev, type)
    );

    create table aud_decision_tree_mapping (
        process_type varchar(255) not null,
        rev integer not null,
        revtype smallint,
        process_definition_id bigint,
        primary key (rev, process_type)
    );

    create table decision_fact (
        id bigint generated by default as identity,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        active boolean not null,
        code varchar(255) not null,
        value varchar(255) not null,
        created_by uuid,
        updated_by uuid,
        process_instance_id uuid not null,
        primary key (id)
    );

    create table decision_fact_details (
        code varchar(255) not null,
        created_at timestamp(6) with time zone not null,
        description varchar(255) not null,
        updated_at timestamp(6) with time zone not null,
        created_by uuid,
        updated_by uuid,
        primary key (code)
    );

    create table decision_fact_fixed (
        id bigint generated by default as identity,
        code varchar(255) not null,
        fact_value varchar(255) not null,
        decision_department varchar(255),
        decline_reason_id varchar(255),
        schema_code varchar(255),
        process_execution_id uuid not null,
        primary key (id)
    );

    create table decision_maker_type (
        decision_fact_details_code varchar(255) not null,
        type varchar(255) not null,
        primary key (decision_fact_details_code, type)
    );

    create table decision_tree_mapping (
        process_type varchar(255) not null,
        mapped_at timestamp(6) with time zone,
        mapped_by uuid,
        process_definition_id bigint,
        primary key (process_type)
    );

    create table execution_data_value (
        process_instance_id uuid not null,
        data_type varchar(255) not null,
        raw_content varchar(4000) not null,
        name varchar(255) not null,
        primary key (process_instance_id, name)
    );

    create table process_definition (
        id bigint generated by default as identity,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        key varchar(255) not null,
        name varchar(255) not null,
        process_definition_id varchar(255) not null,
        status varchar(255) not null,
        version integer not null,
        created_by uuid,
        updated_by uuid,
        primary key (id)
    );

    create table process_execution (
        process_instance_id uuid not null,
        created_at timestamp(6) with time zone not null,
        failure_reason text,
        mode smallint not null,
        owner_id uuid not null,
        process_type varchar(255) not null,
        status varchar(255) not null,
        updated_at timestamp(6) with time zone not null,
        execution_exception_id bigint,
        process_definition_id bigint not null,
        primary key (process_instance_id)
    );

    alter table if exists aud_decision_fact_details 
       add constraint FK3sqrbmad1x5t7han8a4bib8vk 
       foreign key (rev) 
       references aud;

    alter table if exists aud_decision_maker_type 
       add constraint FKj6gkuoh7xyscchreakhkao2ig 
       foreign key (rev) 
       references aud;

    alter table if exists aud_decision_tree_mapping 
       add constraint FK7367hk72hjehujsssac0qb4um 
       foreign key (rev) 
       references aud;

    alter table if exists decision_fact 
       add constraint FKm86kl9xr0y0hcfe7o8instx18 
       foreign key (created_by) 
       references auditor;

    alter table if exists decision_fact 
       add constraint FKfpvap8nr7jhr6dt8ifxfba8k1 
       foreign key (updated_by) 
       references auditor;

    alter table if exists decision_fact 
       add constraint FKpvii9ud1m9dvloxppuuwls4xo 
       foreign key (process_instance_id) 
       references process_execution;

    alter table if exists decision_fact_details 
       add constraint FK2g6agv9713k0nde5e9vauxemi 
       foreign key (created_by) 
       references auditor;

    alter table if exists decision_fact_details 
       add constraint FKfc8x7yr4kv03suqnc1lffox80 
       foreign key (updated_by) 
       references auditor;

    alter table if exists decision_fact_fixed 
       add constraint FKig9v62lmbd14c6jdhvii2479b 
       foreign key (decision_department) 
       references decision_department;

    alter table if exists decision_fact_fixed 
       add constraint FKhlbu9r4xcuuhpuqc22b91sduk 
       foreign key (decline_reason_id) 
       references decline_reason;

    alter table if exists decision_fact_fixed 
       add constraint FKd786l6us0mhabk4gwi1iycqg8 
       foreign key (schema_code) 
       references form_schema;

    alter table if exists decision_fact_fixed 
       add constraint FK71qpcyngb6t0uoi24olvh09vt 
       foreign key (process_execution_id) 
       references process_execution;

    alter table if exists decision_maker_type 
       add constraint FKsk4hvhjq84wm9osgmeivouuyp 
       foreign key (decision_fact_details_code) 
       references decision_fact_details;

    alter table if exists decision_tree_mapping 
       add constraint FKewfpnn5tm4v02eiycckit0lsd 
       foreign key (mapped_by) 
       references auditor;

    alter table if exists decision_tree_mapping 
       add constraint FKmks549vxtmdf5uomq4v0787lr 
       foreign key (process_definition_id) 
       references process_definition;

    alter table if exists execution_data_value 
       add constraint FKf3o5h1i4q49bnvcl4mgauaxh6 
       foreign key (process_instance_id) 
       references process_execution;

    alter table if exists process_definition 
       add constraint FKet0d961kertkn3y1t1378krvl 
       foreign key (created_by) 
       references auditor;

    alter table if exists process_definition 
       add constraint FKitx64mc0vyxb36yflmsofdtqr 
       foreign key (updated_by) 
       references auditor;

    alter table if exists process_execution 
       add constraint FKc8v4hfyym4x9pfannfowl43mi 
       foreign key (execution_exception_id) 
       references exception_entity;

    alter table if exists process_execution 
       add constraint FK3j3vthfgbf5dvxeafoqbl9q5c 
       foreign key (process_definition_id) 
       references process_definition;
