
    create table aud_decline_reason (
        code varchar(255) not null,
        rev integer not null,
        revtype smallint,
        active boolean,
        description varchar(255),
        export_id uuid default gen_random_uuid(),
        primary key (rev, code)
    );

    create table aud_field_mapping (
        id bigint not null,
        rev integer not null,
        revtype smallint,
        data_source_name varchar(255),
        description varchar(255),
        export_id uuid,
        engine_name varchar(255),
        expression text,
        field_name varchar(255),
        metadata varchar(255),
        version bigint,
        primary key (rev, id)
    );

    create table aud_pending_decision (
        id bigint not null,
        rev integer not null,
        revtype smallint,
        comment varchar(1000),
        decision_made_at timestamp(6) with time zone,
        fact varchar(255),
        process_group varchar(255),
        status varchar(255),
        values jsonb,
        decision_department varchar(255),
        decision_made_by uuid,
        decline_reason_id varchar(255),
        holder_id bigint,
        schema_code varchar(255),
        primary key (rev, id)
    );

    create table aud_pending_decision_holder (
        id bigint not null,
        rev integer not null,
        revtype smallint,
        primary key (rev, id)
    );

    create table aud_pending_decision_holder_assignees (
        rev integer not null,
        pending_decision_holder_id bigint not null,
        assignee_id uuid not null,
        department_code varchar(255) not null,
        revtype smallint,
        primary key (pending_decision_holder_id, rev, assignee_id, department_code)
    );

    create table covenant (
        id uuid not null,
        created_at timestamp(6) with time zone not null,
        owner_id uuid not null,
        raw_content varchar(255),
        state varchar(255) not null,
        subject_id uuid not null,
        execution_id bigint,
        metric_id uuid not null,
        specification_id uuid not null,
        primary key (id)
    );

    create table covenant_execution (
        id bigint generated by default as identity,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        period_index integer,
        status varchar(255) not null,
        created_by uuid,
        updated_by uuid,
        exception_id bigint,
        specification_id uuid not null,
        primary key (id)
    );

    create table covenant_execution_covenant (
        covenant_execution bigint not null,
        covenant uuid not null,
        primary key (covenant_execution, covenant)
    );

    create table covenant_specification (
        id uuid not null,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        active boolean not null,
        lineage_id uuid,
        date_time_execution timestamp(6),
        execution_type varchar(255) not null,
        engine_name varchar(255) not null,
        expression text not null,
        holder_type varchar(255) not null,
        name varchar(255) not null,
        number_of_periods integer,
        periodicity varchar(255),
        subject_key varchar(255) not null,
        created_by uuid,
        updated_by uuid,
        anchored_metric_mapping_id uuid,
        mapping_id uuid not null,
        primary key (id)
    );

    create table covenant_specification_product_additive (
        covenant_specification_id uuid not null,
        product_additive_code bigint not null
    );

    create table credit_expected_payment (
        id bigint generated by default as identity,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        amount numeric(19,2),
        currency varchar(3),
        date date not null,
        interest numeric(19,2),
        principal numeric(19,2),
        remaining_interest numeric(19,2),
        remaining_principal numeric(19,2),
        created_by uuid,
        updated_by uuid,
        payment_schedule_id bigint not null,
        primary key (id)
    );

    create table credit_payment_schedule (
        id bigint generated by default as identity,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        currency varchar(3),
        end_date date not null,
        start_date date not null,
        term integer not null,
        total_amount numeric(19,2) not null,
        total_interest numeric(19,2) not null,
        total_principal numeric(19,2) not null,
        created_by uuid,
        updated_by uuid,
        primary key (id)
    );

    create table credit_product (
        id uuid not null,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        active boolean not null,
        lineage_id uuid,
        code varchar(255) not null,
        credit_type varchar(255) not null,
        engine_name varchar(255) not null,
        title varchar(255) not null,
        uuid_contract_template uuid not null,
        created_by uuid,
        updated_by uuid,
        primary key (id)
    );

    create table credit_product_additive (
        id bigint generated by default as identity,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        active boolean not null,
        procuring_type varchar(255) not null,
        created_by uuid,
        updated_by uuid,
        product_id uuid not null,
        primary key (id)
    );

    create table credit_product_additive_offer_engine_map (
        additive_id bigint not null,
        offer_engine uuid not null,
        engine_type varchar(255) not null,
        primary key (additive_id, engine_type)
    );

    create table credit_product_offer_engine_type (
        credit_product_id uuid not null,
        offer_engine_type varchar(255) not null,
        primary key (credit_product_id, offer_engine_type)
    );

    create table decision_department (
        code varchar(255) not null,
        active boolean not null,
        created_at timestamp(6) with time zone not null,
        description varchar(255) not null,
        export_id uuid default gen_random_uuid() not null,
        updated_at timestamp(6) with time zone not null,
        created_by uuid,
        updated_by uuid,
        primary key (code)
    );

    create table decline_reason (
        code varchar(255) not null,
        active boolean not null,
        description varchar(255) not null,
        export_id uuid default gen_random_uuid() not null,
        primary key (code)
    );

    create table document_response_sample (
        id bigint not null,
        document_id uuid not null,
        primary key (id)
    );

    create table feature (
        id uuid not null,
        created_at timestamp(6) with time zone not null,
        data_source_name varchar(255) not null,
        data_type varchar(255) not null,
        mapping_version bigint not null,
        name varchar(255) not null,
        owner_id uuid not null,
        raw_content varchar(4000),
        record_key uuid not null,
        mapping_id bigint not null,
        primary key (id)
    );

    create table field_mapping (
        id bigint generated by default as identity,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        active boolean not null,
        data_source_name varchar(255) not null,
        description varchar(255),
        export_id uuid not null,
        engine_name varchar(255) not null,
        expression text not null,
        field_name varchar(255) not null,
        metadata varchar(255),
        version bigint not null,
        created_by uuid,
        updated_by uuid,
        primary key (id)
    );

    create table metric (
        id uuid not null,
        created_at timestamp(6) with time zone not null,
        data_type varchar(255) not null,
        metric_type varchar(255) not null,
        name varchar(255) not null,
        owner_id uuid not null,
        raw_content varchar(4000),
        mapping_id uuid not null,
        primary key (id)
    );

    create table metric_mapping (
        id uuid not null,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        active boolean not null,
        lineage_id uuid,
        engine_name varchar(255) not null,
        expression text not null,
        metric_entity_type varchar(255) not null,
        name varchar(255) not null,
        created_by uuid,
        updated_by uuid,
        primary key (id)
    );

    create table offer_engine_descriptor (
        id uuid not null,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        active boolean not null,
        lineage_id uuid,
        execution_result_type varchar(255) not null,
        engine_name varchar(255) not null,
        expression text not null,
        name varchar(255) not null,
        created_by uuid,
        updated_by uuid,
        primary key (id)
    );

    create table pending_decision (
        id bigint generated by default as identity,
        comment varchar(1000),
        decision_made_at timestamp(6) with time zone,
        fact varchar(255) not null,
        process_group varchar(255) not null,
        status varchar(255) not null,
        values jsonb,
        decision_department varchar(255),
        decision_made_by uuid,
        decline_reason_id varchar(255),
        holder_id bigint not null,
        schema_code varchar(255),
        primary key (id)
    );

    create table pending_decision_holder (
        id bigint generated by default as identity,
        owner_type varchar(255) not null,
        primary key (id)
    );

    create table pending_decision_holder_assignees (
        pending_decision_holder_id bigint not null,
        assignee_id uuid,
        department_code varchar(255) not null,
        primary key (pending_decision_holder_id, department_code)
    );

    create table reference_amount (
        id bigint generated by default as identity,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        active boolean not null,
        date date,
        export_id uuid default gen_random_uuid() not null,
        index numeric not null,
        currency varchar(3) not null,
        created_by uuid,
        updated_by uuid,
        primary key (id)
    );

    create table reference_rate (
        id bigint generated by default as identity,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        active boolean not null,
        date date,
        export_id uuid default gen_random_uuid() not null,
        index numeric not null,
        abbreviation varchar(255) not null,
        description varchar(255) not null,
        created_by uuid,
        updated_by uuid,
        primary key (id)
    );

    create table response_sample (
        response_sample_type varchar(31) not null,
        id bigint generated by default as identity,
        created_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone not null,
        data_type varchar(255) not null,
        created_by uuid,
        updated_by uuid,
        primary key (id)
    );

    create table subject_external_data (
        id uuid not null,
        owner_id uuid not null,
        social varchar(255),
        requested_at timestamp(6) with time zone not null,
        data_type varchar(255) not null,
        valid boolean not null,
        document_id uuid not null,
        primary key (id)
    );

    create table user_account_decision_department (
        user_account_id uuid not null,
        department varchar(255) not null,
        primary key (user_account_id)
    );

    alter table if exists decision_department 
       drop constraint if exists UK32ye67ndp8vpc4ty94h18e2c3;

    alter table if exists decision_department 
       add constraint UK32ye67ndp8vpc4ty94h18e2c3 unique (export_id);

    alter table if exists decline_reason 
       drop constraint if exists UKen32go86ki6aic1cyntmp9wt6;

    alter table if exists decline_reason 
       add constraint UKen32go86ki6aic1cyntmp9wt6 unique (export_id);

    alter table if exists document_response_sample 
       drop constraint if exists UKce3re62l70fj8wjeq96mq7ox2;

    alter table if exists document_response_sample 
       add constraint UKce3re62l70fj8wjeq96mq7ox2 unique (document_id);

    alter table if exists field_mapping 
       drop constraint if exists UKsplqk0lwh60bi7jd59xbdju5e;

    alter table if exists field_mapping 
       add constraint UKsplqk0lwh60bi7jd59xbdju5e unique (export_id);

    alter table if exists reference_amount 
       drop constraint if exists reference_amount_uniq_date;

    alter table if exists reference_amount 
       add constraint reference_amount_uniq_date unique (date);

    alter table if exists reference_amount 
       drop constraint if exists UKnoqp3da5l0qksmsd7twx14u05;

    alter table if exists reference_amount 
       add constraint UKnoqp3da5l0qksmsd7twx14u05 unique (export_id);

    alter table if exists reference_rate 
       drop constraint if exists UKjlv8pqdwgxy7r681kt55k6v0y;

    alter table if exists reference_rate 
       add constraint UKjlv8pqdwgxy7r681kt55k6v0y unique (export_id);

    alter table if exists subject_external_data 
       drop constraint if exists UKb5a09q9uq9x7jw0tiy2ecrpk5;

    alter table if exists subject_external_data 
       add constraint UKb5a09q9uq9x7jw0tiy2ecrpk5 unique (document_id);

    alter table if exists aud_decline_reason 
       add constraint FKf7g4olsc237elbdc3e7on5o9x 
       foreign key (rev) 
       references aud;

    alter table if exists aud_field_mapping 
       add constraint FKrgbu9h94l2xjuud08g5q8vr5l 
       foreign key (rev) 
       references aud;

    alter table if exists aud_pending_decision 
       add constraint FKi8ulkx89bd8dwjlut15p7dgq1 
       foreign key (rev) 
       references aud;

    alter table if exists aud_pending_decision_holder 
       add constraint FKe03c9ey34d45g51gso6vlhb96 
       foreign key (rev) 
       references aud;

    alter table if exists aud_pending_decision_holder_assignees 
       add constraint FK3bhipa9ptp62eh86oxd9wrq36 
       foreign key (rev) 
       references aud;

    alter table if exists covenant 
       add constraint FKhfoupys0q6mht7ue4mqh3wmpo 
       foreign key (execution_id) 
       references covenant_execution;

    alter table if exists covenant 
       add constraint FK4yf7wcqwapb3fq2x400e55eis 
       foreign key (metric_id) 
       references metric;

    alter table if exists covenant 
       add constraint FKdtbh6ytt14aqpp3p1gloes4kx 
       foreign key (specification_id) 
       references covenant_specification;

    alter table if exists covenant_execution 
       add constraint FK6828g9wwipddd0n735em0oxl3 
       foreign key (created_by) 
       references auditor;

    alter table if exists covenant_execution 
       add constraint FKly2vcrf9ygoth5fu9tue1kqvo 
       foreign key (updated_by) 
       references auditor;

    alter table if exists covenant_execution 
       add constraint FK20fea6gwxcspr7t29m1yvd08p 
       foreign key (exception_id) 
       references exception_entity;

    alter table if exists covenant_execution 
       add constraint FKjmi65dqlhjlggi4nksegxgc0e 
       foreign key (specification_id) 
       references covenant_specification;

    alter table if exists covenant_execution_covenant 
       add constraint FK8f56t9m0epgxhou5lhximl7qk 
       foreign key (covenant) 
       references covenant;

    alter table if exists covenant_execution_covenant 
       add constraint FK9poj8wawwpwnk4r3e7rmf954h 
       foreign key (covenant_execution) 
       references covenant_execution;

    alter table if exists covenant_specification 
       add constraint FK59n0dhn34kwt0b3l9dv9bjgqw 
       foreign key (created_by) 
       references auditor;

    alter table if exists covenant_specification 
       add constraint FKtq9outn9yp5ew0h1kuncq0a96 
       foreign key (updated_by) 
       references auditor;

    alter table if exists covenant_specification 
       add constraint FKasw9101w0im08dab59hcy9gkq 
       foreign key (anchored_metric_mapping_id) 
       references metric_mapping;

    alter table if exists covenant_specification 
       add constraint FKspqnbmjfi1bvsrkynkatf2sv5 
       foreign key (mapping_id) 
       references metric_mapping;

    alter table if exists covenant_specification_product_additive 
       add constraint FK20boc6rvnblpj1uqow4hqj2no 
       foreign key (covenant_specification_id) 
       references covenant_specification;

    alter table if exists credit_expected_payment 
       add constraint FK6cb551vyhugr0cynddkk0qgh8 
       foreign key (created_by) 
       references auditor;

    alter table if exists credit_expected_payment 
       add constraint FK9gv69e1f3fe4xqudqjf6h7l2d 
       foreign key (updated_by) 
       references auditor;

    alter table if exists credit_expected_payment 
       add constraint FKs26jvj8lt6lkyt96e9t00vps 
       foreign key (payment_schedule_id) 
       references credit_payment_schedule;

    alter table if exists credit_payment_schedule 
       add constraint FKouv1bo7nkcg76f8qqin6xkc2e 
       foreign key (created_by) 
       references auditor;

    alter table if exists credit_payment_schedule 
       add constraint FKkfjkwbjtkddl63bnqmmm2siu7 
       foreign key (updated_by) 
       references auditor;

    alter table if exists credit_product 
       add constraint FKqxccher4adq469asediuitmc7 
       foreign key (created_by) 
       references auditor;

    alter table if exists credit_product 
       add constraint FK4d3i5q2myq4gmo4cw9398ji7v 
       foreign key (updated_by) 
       references auditor;

    alter table if exists credit_product_additive 
       add constraint FKpakgxfrne3qw5v9kfcf7o4o5x 
       foreign key (created_by) 
       references auditor;

    alter table if exists credit_product_additive 
       add constraint FKdl0m4yh4cyqcg7b5emm19lu7 
       foreign key (updated_by) 
       references auditor;

    alter table if exists credit_product_additive 
       add constraint FKjcsi8a61jx2n2guxjqs3i7yvm 
       foreign key (product_id) 
       references credit_product;

    alter table if exists credit_product_additive_offer_engine_map 
       add constraint FK5uklt11i7lkffv7k1kngxjg9g 
       foreign key (additive_id) 
       references credit_product_additive;

    alter table if exists credit_product_offer_engine_type 
       add constraint FK62q44oetnwd6pmc3qhjr8l19d 
       foreign key (credit_product_id) 
       references credit_product;

    alter table if exists decision_department 
       add constraint FKj4twt4l96pawwox4b3r8ngx1g 
       foreign key (created_by) 
       references auditor;

    alter table if exists decision_department 
       add constraint FK8du34r542flpwit4wq91c6yhb 
       foreign key (updated_by) 
       references auditor;

    alter table if exists document_response_sample 
       add constraint FKt48p3trs7rowfxv70w1aceaxc 
       foreign key (document_id) 
       references document;

    alter table if exists document_response_sample 
       add constraint FK1naawaf6ysg0ecv5xqpst9va2 
       foreign key (id) 
       references response_sample;

    alter table if exists feature 
       add constraint FKh6a07yagvt3m2s1uyv3ni6329 
       foreign key (mapping_id) 
       references field_mapping;

    alter table if exists field_mapping 
       add constraint FKoi8jkssa9c4esp55tn25m93wy 
       foreign key (created_by) 
       references auditor;

    alter table if exists field_mapping 
       add constraint FKlepp7y5cuud9agwu0im7wg673 
       foreign key (updated_by) 
       references auditor;

    alter table if exists metric 
       add constraint FKcnu2o6y3d1apbb8q4t419gwo3 
       foreign key (mapping_id) 
       references metric_mapping;

    alter table if exists metric_mapping 
       add constraint FKfyrr6u6py0cug1gqypgymhft9 
       foreign key (created_by) 
       references auditor;

    alter table if exists metric_mapping 
       add constraint FKpupqclydafn6ftsh61vbhicse 
       foreign key (updated_by) 
       references auditor;

    alter table if exists offer_engine_descriptor 
       add constraint FKq194ngnl8jjt3u9harnersq5p 
       foreign key (created_by) 
       references auditor;

    alter table if exists offer_engine_descriptor 
       add constraint FKhh8d39cl1d9b2gtihe2cq8pan 
       foreign key (updated_by) 
       references auditor;

    alter table if exists pending_decision 
       add constraint FKx71mbc2nk89wtwltvnb10m0c 
       foreign key (decision_department) 
       references decision_department;

    alter table if exists pending_decision 
       add constraint FKdc8d5wyie7y48206bel2x6bs5 
       foreign key (decision_made_by) 
       references auditor;

    alter table if exists pending_decision 
       add constraint FK9ebi8la1sk3s7kfl6pfcgq2ro 
       foreign key (decline_reason_id) 
       references decline_reason;

    alter table if exists pending_decision 
       add constraint FKm9xne529rssxce323lbsy6yy9 
       foreign key (holder_id) 
       references pending_decision_holder;

    alter table if exists pending_decision 
       add constraint FK5hbypc0flpdo73u6ypbntsgvk 
       foreign key (schema_code) 
       references form_schema;

    alter table if exists pending_decision_holder_assignees 
       add constraint FKm8ekrfelu7fk79iplo4t29crs 
       foreign key (pending_decision_holder_id) 
       references pending_decision_holder;

    alter table if exists reference_amount 
       add constraint FKfad3s93iyxkb3rn7ulxjkbcxg 
       foreign key (created_by) 
       references auditor;

    alter table if exists reference_amount 
       add constraint FK7jeggd8xno9u514vegp3bcu3v 
       foreign key (updated_by) 
       references auditor;

    alter table if exists reference_rate 
       add constraint FKmxesxy2csj01btcy5d8tg8rwv 
       foreign key (created_by) 
       references auditor;

    alter table if exists reference_rate 
       add constraint FKc5tjerwwe717d4kjmvyb6mp1 
       foreign key (updated_by) 
       references auditor;

    alter table if exists response_sample 
       add constraint FKcdi2e1m9ajy2q9uhp4ipfxb6q 
       foreign key (created_by) 
       references auditor;

    alter table if exists response_sample 
       add constraint FKtk7sfdervqpuw8tf57e4o78rg 
       foreign key (updated_by) 
       references auditor;

    alter table if exists subject_external_data 
       add constraint FKmnrpa47j3jllfe1qij80d85n1 
       foreign key (document_id) 
       references document;

    alter table if exists user_account_decision_department 
       add constraint FK8ybrl26sm8lvjjv40obm1jpap 
       foreign key (department) 
       references decision_department;

    alter table if exists user_account_decision_department 
       add constraint FK6uton7lh53ou6j12394g6r72o 
       foreign key (user_account_id) 
       references user_account;
